FROM ruby:2.6.0

ENV LANG C.UTF-8

RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get update -qq && \
 apt-get install -y --no-install-recommends \
  build-essential \
  vim \
  nodejs \
  libpq-dev \
  nfs-common \
  mysql-client \
  libfontconfig1 && \
  rm -rf /var/lib/apt/lists/*

ENV ENTRYKIT_VERSION 0.4.0

RUN wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && mv entrykit /bin/entrykit \
  && chmod +x /bin/entrykit \
  && entrykit --symlink

RUN mkdir /app


WORKDIR /app


COPY . /app/

# add EFS mount setting in /etc/fstab 
# RUN echo "fs-21fc2e00.efs.ap-northeast-1.amazonaws.com:/  /app/files efs defaults,_netdev 0 0" >> /etc/fstab

RUN bundle config build.nokogiri --use-system-libraries
RUN bundle install -j3

ENTRYPOINT [ \
  "prehook", "ruby -v", "--" \
  ]
#  "prehook", "npm install --no-optional", "--"
#  "prehook", "bundle install -j3 ", "--" ]
